name: "Build and push"
description: "Builds and pushes turbo packages as Docker images to GitHub container registry"

inputs:
  package:
    description: "Name of the package to build and push"
    required: true
  registry-username:
    description: "Username for ghcr.io"
    required: true
  registry-password:
    description: "Password for ghcr.io"
    required: true
  build-arg-1:
    description: "Docker image build argument 1"
    required: false
  build-arg-2:
    description: "Docker image build argument 2"
    required: false
  build-arg-3:
    description: "Docker image build argument 3"
    required: false
  build-arg-4:
    description: "Docker image build argument 4"
    required: false
  build-arg-5:
    description: "Docker image build argument 5"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: Build and push ${{ inputs.package }} Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.docker/Dockerfile.${{ inputs.package }}
        push: true
        build-args: |
          ${{ input.build-arg-1 }}
          ${{ input.build-arg-2 }}
          ${{ input.build-arg-3 }}
          ${{ input.build-arg-4 }}
          ${{ input.build-arg-5 }}
        tags: |
          ghcr.io/${{ github.repository }}/${{ inputs.package }}:latest
          ghcr.io/${{ github.repository }}/${{ inputs.package }}:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    - # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
