# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Restore node_modules cache
        uses: actions/cache@v2.1.5
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - name: Install packages
        run: yarn --frozen-lockfile
      # - name: All tests
      #   run: yarn test-coverage --cache-dir=".turbo"
      # - name: Add coverage comment
      #   continue-on-error: true
      #   uses: eeshdarthvader/code-coverage-assistant@master
      #   with:
      #       github-token: ${{ secrets.GITHUB_TOKEN }}
      #       monorepo-base-path: './packages'
      - name: Build packages
        run: yarn run build
      # - name: Build Docker image for Storefront
      #   run: docker build ./apps/storefront/ --tag project/storefront:$(date +%s)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push storefront Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/storefront
          push: true
          tags: ghcr.io/${{ github.repository }}/storefront:latest
